### ISSUE TITLE
Extend Support for `.gcloudignore`

### ISSUE THREAD

**Issue by confused-Techie** [ldez/atom-language-ignore#5]
While I realize this package was originally made for Atom, it is available to install on [Pulsar](https://github.com/pulsar-edit) the new fork of Atom.

I see this package hasn't received any updates for some time, but that the author is still active. 

I was wondering if support for `.gcloudignore` files could be added, they work just like `.gitignore`. And if so I'd be more than happy to do so in a PR, but also wanted to see if done, would the package author be willing to update the package on Pulsar as well.

Thanks a ton for any response!

**Comment by ldez** [comment]
Hello,
yes, the support for `.gcloudignore` can be added.
The repository configuration no longer allows publishing a version automatically, but I can do it manually if you provide the Pulsar workflow.

**Comment by confused-Techie** [comment]
@ldez That's fantastic news!

You could do it automatically, or completely manually.

* Manually: Installing Pulsar to your workstation, then using `pulsar -p publish minor` in the same directory as your package. To do this of course you'll need to have an account with Pulsar that you can make on the [Pulsar Website](https://web.pulsar-edit.dev/login). And prior to publishing get your API key from the website after creating your account and run `pulsar -p login --token=<API_TOKEN>`. And after this you 

## Automatically
1) Install Pulsar on your workstation
2) Create an account on the [Pulsar Website](https://web.pulsar-edit.dev/login)
3) Take your API token from the website and run `pulsar -p login --token=<API_TOKEN>`
4) Then within the project directory run `pulsar -p publish minor`

## Manually
1) Update your package's `package.json` with the next version in the `version` key
2) Tag a release on GitHub with the same new version
3) Create an account on the [Pulsar Website](https://web.pulsar-edit.dev/login)
4) Take your API token from the website and save it for the next step
5) Make a `POST` request to `https://api.pulsar-edit.dev/api/packages/language-ignore/versions` with the Header value `"Authorization": "<API_TOKEN>"` set.

But I know the above might be a lot. But would love to see you contributing to the package on Pulsar, if you'd rather I'd also be more than happy to help out! Since anyone given write access to the repo is able to publish to pulsar as well. But otherwise I hope the above steps work just fine for you. And I'll make a PR here with the suggested changes! 
Thanks again for the response!

**Comment by ldez** [comment]
When I say "automatically", I think through the CI :wink: 

Thank you, I will publish the package.

**Comment by confused-Techie** [comment]
> When I say "automatically", I think through the CI 😉
> 
> Thank you, I will publish the package.

Yeah fair enough, suppose I should've said, 'Easier' as it just does some steps for you. But thanks a ton!
