### ISSUE TITLE
Update Readme for Pulsar

### ISSUE THREAD

**Issue by confused-Techie** [ldez/atom-language-ignore#7]
Feel free to close this one, if it's not something you're worried about.

But just wanted to ask if you'd also accept another PR from me updating the readme of this project, as the Atom badges are now broken, and Atom data now out of date.

The simplest thing that can be done is remove the failing Atom badges, and update the installation docs, and replace usage of `Atom` with `Pulsar/Atom`.

And while my [PR](https://github.com/badges/shields/pull/8767) to get badges added onto Shields.io is still in review, Pulsar does support what's Social Image cards for packages, meaning we could place something like this at the top of your Readme:

[![language-ignore](https://image.pulsar-edit.dev/packages/language-ignore)](https://web.pulsar-edit.dev/packages/language-ignore)

> Which I'll be adding theme support for these later today.

If that's something you're willing to see happen I'm more than happy to submit a PR for it, just wanted to make sure that's something you're alright with. Thanks again for everything!

**Comment by ldez** [comment]
Feel free to update the readme.
Pulsar is open-source, so it fits with my philosophy.

**Comment by confused-Techie** [comment]
Would you also like me to replace the badges for Atom with the image from above? Or should I just remove the Atom badges.

But glad to hear! I'll give this a go shortly
